apiVersion: apps/v1
kind: Deployment
metadata:
  name: discovery-deployment
  labels:
    app: discovery-server
spec:
  replicas: 1 # Для Eureka зазвичай достатньо однієї репліки в лабораторних умовах
  selector:
    matchLabels:
      app: discovery-server
  template:
    metadata:
      labels:
        app: discovery-server
    spec:
      containers:
        - name: discovery-server
          image: crypto-trading/discovery-server:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8761 # Порт з application.properties
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: discovery-service # Важливо: це ім'я використовують інші мікросервіси для підключення
spec:
  selector:
    app: discovery-server
  ports:
    - protocol: TCP
      port: 8761
      targetPort: 8761
  type: ClusterIP
